baseURL: "https://muyidonblog.com"
languageCode: "en-us"
title: "M.K Blog"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "https://twitter.com/muyidon"
  github: "https://github.com/muyidon"
  instagram: "https://instagram.com/muyidon"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
